package fleetclient

import (
	"context"
	"crypto/ed25519"
	"encoding/hex"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"

	"statskey/fleetd/internal/canon"
	"statskey/fleetd/internal/keys"
)

// protocolVectors are generated by scripts/gen-fixtures.cjs from the JS
// fleetAuth.js implementation.
type protocolVectors struct {
	DeviceSeedHex            string `json:"deviceSeedHex"`
	CoordinatorSeedHex       string `json:"coordinatorSeedHex"`
	DeviceID                 string `json:"deviceId"`
	CoordinatorKeyID         string `json:"coordinatorKeyId"`
	CoordinatorPublicKeySpki string `json:"coordinatorPublicKeySpki"`
	Request                  struct {
		Action    string         `json:"action"`
		Payload   map[string]any `json:"payload"`
		IssuedAt  int64          `json:"issuedAt"`
		ExpiresAt int64          `json:"expiresAt"`
		RequestID string         `json:"requestId"`
		Envelope  map[string]any `json:"envelope"`
	} `json:"request"`
	Response struct {
		Result   map[string]any `json:"result"`
		Envelope map[string]any `json:"envelope"`
	} `json:"response"`
}

func loadVectors(t *testing.T) protocolVectors {
	t.Helper()
	raw, err := os.ReadFile("testdata/protocol_vectors.json")
	if err != nil {
		t.Fatalf("read vectors: %v (run scripts/gen-fixtures.cjs)", err)
	}
	var v protocolVectors
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatal(err)
	}
	return v
}

func seedKey(t *testing.T, seedHex string) ed25519.PrivateKey {
	t.Helper()
	seed, err := hex.DecodeString(seedHex)
	if err != nil {
		t.Fatal(err)
	}
	priv, err := keys.PrivateFromSeed(seed)
	if err != nil {
		t.Fatal(err)
	}
	return priv
}

// normalizeFixture converts fixture JSON (decoded by encoding/json into
// float64s) into canon-compatible values with int64s.
func normalizeFixture(t *testing.T, v map[string]any) map[string]any {
	t.Helper()
	raw, err := json.Marshal(v)
	if err != nil {
		t.Fatal(err)
	}
	out, err := canon.FromJSON(raw)
	if err != nil {
		t.Fatal(err)
	}
	return out.(map[string]any)
}

func TestRequestEnvelopeInterop(t *testing.T) {
	v := loadVectors(t)
	priv := seedKey(t, v.DeviceSeedHex)
	payload := normalizeFixture(t, v.Request.Payload)

	// Rebuild the envelope with identical inputs: the signature must be
	// byte-identical to the node-produced one (deterministic Ed25519).
	env, err := CreateSignedRequest(priv, v.DeviceID, v.Request.Action, payload, v.Request.IssuedAt, v.Request.ExpiresAt, v.Request.RequestID)
	if err != nil {
		t.Fatal(err)
	}
	if env["signature"] != v.Request.Envelope["signature"] {
		t.Fatalf("signature mismatch:\n go:   %v\n node: %v", env["signature"], v.Request.Envelope["signature"])
	}
	// Every field matches.
	for _, k := range []string{"protocolVersion", "deviceId", "requestId", "action", "payloadDigest"} {
		gotRaw, _ := json.Marshal(env[k])
		wantRaw, _ := json.Marshal(v.Request.Envelope[k])
		if string(gotRaw) != string(wantRaw) {
			t.Fatalf("field %s: go %s node %s", k, gotRaw, wantRaw)
		}
	}
	// Go verifies the node-produced envelope (coordinator side).
	nodeEnv := normalizeFixture(t, v.Request.Envelope)
	if err := VerifySignedRequest(keys.Public(priv), nodeEnv, payload, "job.poll", v.Request.IssuedAt+1000); err != nil {
		t.Fatalf("verify node request: %v", err)
	}
	// Wrong action / tampered payload / expired all fail.
	if err := VerifySignedRequest(keys.Public(priv), nodeEnv, payload, "job.claim", v.Request.IssuedAt+1000); err == nil {
		t.Fatal("action mismatch accepted")
	}
	if err := VerifySignedRequest(keys.Public(priv), nodeEnv, map[string]any{"maxJobs": int64(2)}, "job.poll", v.Request.IssuedAt+1000); err == nil {
		t.Fatal("payload mismatch accepted")
	}
	if err := VerifySignedRequest(keys.Public(priv), nodeEnv, payload, "job.poll", v.Request.ExpiresAt+1); err == nil {
		t.Fatal("expired request accepted")
	}
}

func TestResponseVerificationInterop(t *testing.T) {
	v := loadVectors(t)
	coordPub, _, err := keys.ParsePublicKeySPKI(v.CoordinatorPublicKeySpki)
	if err != nil {
		t.Fatal(err)
	}
	result := normalizeFixture(t, v.Response.Result)
	env := normalizeFixture(t, v.Response.Envelope)
	now := v.Request.IssuedAt + 1000

	if err := VerifySignedResponse(coordPub, v.CoordinatorKeyID, env, v.DeviceID, v.Request.RequestID, "job.poll", result, now); err != nil {
		t.Fatalf("verify node response: %v", err)
	}
	// Wrong key ID.
	if err := VerifySignedResponse(coordPub, "other-key", env, v.DeviceID, v.Request.RequestID, "job.poll", result, now); err == nil {
		t.Fatal("wrong key id accepted")
	}
	// Tampered result.
	tampered := normalizeFixture(t, v.Response.Result)
	tampered["serverTime"] = int64(1)
	if err := VerifySignedResponse(coordPub, v.CoordinatorKeyID, env, v.DeviceID, v.Request.RequestID, "job.poll", tampered, now); err == nil {
		t.Fatal("tampered result accepted")
	}
	// Wrong request ID (replay binding).
	if err := VerifySignedResponse(coordPub, v.CoordinatorKeyID, env, v.DeviceID, "req_ffffffffffffffffffffffffffffffff", "job.poll", result, now); err == nil {
		t.Fatal("wrong request id accepted")
	}
	// Expired.
	if err := VerifySignedResponse(coordPub, v.CoordinatorKeyID, env, v.DeviceID, v.Request.RequestID, "job.poll", result, v.Request.ExpiresAt+100000); err == nil {
		t.Fatal("expired response accepted")
	}
	// Wrong key.
	other, _ := keys.Generate()
	if err := VerifySignedResponse(keys.Public(other), v.CoordinatorKeyID, env, v.DeviceID, v.Request.RequestID, "job.poll", result, now); err == nil {
		t.Fatal("wrong key accepted")
	}
}

// TestEndToEnd runs the client against a loopback coordinator that verifies
// the request and signs the response with a pinned test key.
func TestEndToEnd(t *testing.T) {
	devicePriv, _ := keys.Generate()
	coordPriv, _ := keys.Generate()
	coordSPKI, err := keys.SPKIBase64url(keys.Public(coordPriv))
	if err != nil {
		t.Fatal(err)
	}
	deviceID, err := keys.DeviceID(keys.Public(devicePriv))
	if err != nil {
		t.Fatal(err)
	}
	var nowMs int64 = 1_780_000_000_000

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		var body struct {
			Action   string         `json:"action"`
			Payload  map[string]any `json:"payload"`
			Envelope map[string]any `json:"envelope"`
		}
		raw, _ := io.ReadAll(io.LimitReader(r.Body, 1<<20))
		if err := json.Unmarshal(raw, &body); err != nil {
			w.WriteHeader(400)
			return
		}
		// Verify the device request like the coordinator would.
		payloadNorm := normalizeFixture(t, body.Payload)
		envNorm := normalizeFixture(t, body.Envelope)
		if err := VerifySignedRequest(keys.Public(devicePriv), envNorm, payloadNorm, body.Action, nowMs); err != nil {
			w.WriteHeader(401)
			json.NewEncoder(w).Encode(map[string]any{"error": map[string]any{"code": "invalid_signature", "message": "bad sig"}})
			return
		}
		result := map[string]any{"jobs": []any{}, "serverTime": nowMs + 5}
		// Sign the response.
		respEnv := signResponse(t, coordPriv, "coord-1", deviceID, envNorm["requestId"].(string), body.Action, result, nowMs)
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]any{"data": map[string]any{
			"action":            body.Action,
			"deviceId":          deviceID,
			"requestId":         envNorm["requestId"],
			"result":            result,
			"responseSignature": respEnv,
		}})
	}))
	defer srv.Close()

	pub, _, err := keys.ParsePublicKeySPKI(coordSPKI)
	if err != nil {
		t.Fatal(err)
	}
	client, err := NewClient(Client{
		Endpoint:          srv.URL,
		DeviceID:          deviceID,
		PrivateKey:        devicePriv,
		CoordinatorKeyID:  "coord-1",
		CoordinatorPubKey: pub,
		AllowLoopback:     true,
		Now:               func() int64 { return nowMs },
	})
	if err != nil {
		t.Fatal(err)
	}
	result, err := client.Do(context.Background(), "job.poll", map[string]any{"maxJobs": int64(1)})
	if err != nil {
		t.Fatalf("Do: %v", err)
	}
	rm, ok := result.(map[string]any)
	if !ok || rm["serverTime"] != int64(nowMs+5) {
		t.Fatalf("result: %v", result)
	}
}

func signResponse(t *testing.T, priv ed25519.PrivateKey, keyID, deviceID, requestID, action string, result map[string]any, nowMs int64) map[string]any {
	t.Helper()
	digest, err := canon.Digest(result)
	if err != nil {
		t.Fatal(err)
	}
	unsigned := map[string]any{
		"domain":          "statskey.fleet.response.v1",
		"protocolVersion": int64(AuthVersion),
		"keyId":           keyID,
		"deviceId":        deviceID,
		"requestId":       requestID,
		"action":          action,
		"issuedAt":        nowMs,
		"expiresAt":       nowMs + 60_000,
		"resultDigest":    digest,
	}
	raw, err := canon.Encode(unsigned)
	if err != nil {
		t.Fatal(err)
	}
	sig, err := keys.EncodeSignature(keys.Sign(priv, raw))
	if err != nil {
		t.Fatal(err)
	}
	delete(unsigned, "domain")
	unsigned["signature"] = sig
	return unsigned
}

func TestNormalizeEndpoint(t *testing.T) {
	if _, err := NormalizeEndpoint("https://fleet.example.com/device", false); err != nil {
		t.Fatal(err)
	}
	// Trailing slashes trimmed.
	got, err := NormalizeEndpoint("https://fleet.example.com/device/", false)
	if err != nil || !strings.HasSuffix(got, "/device") {
		t.Fatalf("trailing: %q %v", got, err)
	}
	for _, bad := range []string{
		"http://fleet.example.com",
		"https://user:pass@fleet.example.com",
		"https://fleet.example.com/?x=1",
		"https://fleet.example.com/#frag",
		"https://fleet.example.com/a/../b",
		"not a url",
		"",
	} {
		if _, err := NormalizeEndpoint(bad, false); err == nil {
			t.Fatalf("accepted %q", bad)
		}
	}
	// Loopback http only with allowLoopback.
	if _, err := NormalizeEndpoint("http://127.0.0.1:8080", false); err == nil {
		t.Fatal("loopback http without allowance")
	}
	if _, err := NormalizeEndpoint("http://127.0.0.1:8080", true); err != nil {
		t.Fatalf("loopback http with allowance: %v", err)
	}
}

func TestErrorResponseMapping(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(403)
		json.NewEncoder(w).Encode(map[string]any{"error": map[string]any{"code": "device_suspended", "message": "suspended by owner"}})
	}))
	defer srv.Close()
	priv, _ := keys.Generate()
	devID, _ := keys.DeviceID(keys.Public(priv))
	client, err := NewClient(Client{
		Endpoint: srv.URL, DeviceID: devID, PrivateKey: priv,
		CoordinatorKeyID: "coord-1", CoordinatorPubKey: keys.Public(priv),
		AllowLoopback: true,
	})
	if err != nil {
		t.Fatal(err)
	}
	_, err = client.Do(context.Background(), "job.poll", map[string]any{})
	var re *RequestError
	if !errors.As(err, &re) {
		t.Fatalf("err type: %T", err)
	}
	if re.Code != "device_suspended" || re.Status != 403 {
		t.Fatalf("mapped error: %+v", re)
	}
}
