package canon

import (
	"bytes"
	"encoding/json"
	"errors"
	"os"
	"strings"
	"testing"
)

// canonicalVectors are generated by scripts/gen-fixtures.cjs from the actual
// fleetAuth.js implementation. Each vector carries the JS value, the exact
// canonical bytes, and the SHA-256 digest the JS code computes.
type vectorFile struct {
	Canonical []struct {
		Name   string          `json:"name"`
		Value  json.RawMessage `json:"value"`
		JSON   string          `json:"json"`
		SHA256 string          `json:"sha256"`
	} `json:"canonical"`
}

func loadVectors(t *testing.T) vectorFile {
	t.Helper()
	raw, err := os.ReadFile("testdata/canonical_vectors.json")
	if err != nil {
		t.Fatalf("read vectors: %v (run scripts/gen-fixtures.cjs)", err)
	}
	var vf vectorFile
	if err := json.Unmarshal(raw, &vf); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}
	if len(vf.Canonical) == 0 {
		t.Fatal("no vectors")
	}
	return vf
}

// decodeVectorValue parses the vector's "value" field into Go values using
// integer-preserving decoding.
func decodeVectorValue(t *testing.T, raw json.RawMessage) any {
	t.Helper()
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.UseNumber()
	var v any
	if err := dec.Decode(&v); err != nil {
		t.Fatalf("decode vector value: %v", err)
	}
	return convertJSONNumbers(t, v)
}

func convertJSONNumbers(t *testing.T, v any) any {
	t.Helper()
	switch t2 := v.(type) {
	case json.Number:
		n, err := t2.Int64()
		if err != nil {
			t.Fatalf("vector contains non-integer number %q", t2)
		}
		return n
	case []any:
		for i := range t2 {
			t2[i] = convertJSONNumbers(t, t2[i])
		}
		return t2
	case map[string]any:
		for k := range t2 {
			t2[k] = convertJSONNumbers(t, t2[k])
		}
		return t2
	}
	return v
}

func TestConformanceWithJS(t *testing.T) {
	vf := loadVectors(t)
	for _, vec := range vf.Canonical {
		t.Run(vec.Name, func(t *testing.T) {
			v := decodeVectorValue(t, vec.Value)
			got, err := Encode(v)
			if err != nil {
				t.Fatalf("Encode: %v", err)
			}
			if string(got) != vec.JSON {
				t.Fatalf("canonical mismatch:\n go: %s\n js: %s", got, vec.JSON)
			}
			d, err := Digest(v)
			if err != nil {
				t.Fatalf("Digest: %v", err)
			}
			if d != vec.SHA256 {
				t.Fatalf("digest mismatch: go %s js %s", d, vec.SHA256)
			}
			// Strict parse must accept and round-trip exactly.
			parsed, err := Parse([]byte(vec.JSON))
			if err != nil {
				t.Fatalf("Parse(js output): %v", err)
			}
			re, err := Encode(parsed)
			if err != nil {
				t.Fatalf("re-encode: %v", err)
			}
			if string(re) != vec.JSON {
				t.Fatalf("round-trip mismatch:\n got:  %s\n want: %s", re, vec.JSON)
			}
		})
	}
}

func TestEncoderRejects(t *testing.T) {
	cases := []struct {
		name string
		v    any
		want error
	}{
		{"float", 1.5, ErrFloat},
		{"float-integral", float64(5), ErrFloat},
		{"unsafe-int", int64(1) << 60, ErrUnsafeInteger},
		{"unsafe-uint", uint64(1) << 60, ErrUnsafeInteger},
		{"negative-unsafe", -int64(1) << 60, ErrUnsafeInteger},
		{"u2028", "a b", ErrLineSeparator},
		{"u2029", "a b", ErrLineSeparator},
		{"invalid-utf8", string([]byte{0xff, 0xfe}), ErrInvalidString},
		{"struct", struct{}{}, ErrUnsupportedVal},
		{"u2028-key", map[string]any{"a b": 1}, ErrLineSeparator},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := Encode(tc.v)
			if !errors.Is(err, tc.want) {
				t.Fatalf("Encode(%v) error = %v, want %v", tc.v, err, tc.want)
			}
		})
	}

	// Depth 13 must fail (12 is allowed, covered by conformance vector).
	deep := any("leaf")
	for i := 0; i < 13; i++ {
		deep = []any{deep}
	}
	if _, err := Encode(deep); !errors.Is(err, ErrTooDeep) {
		t.Fatalf("depth 13: got %v", err)
	}
	// 513 items must fail.
	big := make([]any, 513)
	if _, err := Encode(big); !errors.Is(err, ErrTooManyItems) {
		t.Fatalf("513 items: got %v", err)
	}
	bigObj := map[string]any{}
	for i := 0; i < 513; i++ {
		bigObj[strings.Repeat("k", 1)+string(rune('a'+i%26))+string(rune('a'+i/26))] = i
	}
	if _, err := Encode(bigObj); !errors.Is(err, ErrTooManyItems) {
		t.Fatalf("513 keys: got %v", err)
	}
}

func TestParserRejects(t *testing.T) {
	cases := []struct {
		name  string
		input string
		want  error
	}{
		{"empty", "", ErrSyntax},
		{"whitespace", `{ "a": 1}`, ErrSyntax},
		{"whitespace-only", "  ", ErrSyntax},
		{"trailing-garbage", `true x`, ErrTrailing},
		{"trailing-newline", "true\n", ErrTrailing},
		{"float", `1.5`, ErrFloat},
		{"float-exp", `1e3`, ErrFloat},
		{"float-exp-plus", `1e+3`, ErrFloat},
		{"negative-zero", `-0`, ErrSyntax},
		{"leading-zero", `01`, ErrTrailing},
		{"plus", `+1`, ErrSyntax},
		{"dup-keys", `{"a":1,"a":2}`, ErrDuplicateKeys},
		{"unsorted-keys", `{"b":1,"a":2}`, ErrDuplicateKeys},
		{"unsorted-utf16", "{\"\":1,\"\U00010000\":2}", ErrDuplicateKeys},
		{"trailing-comma-array", `[1,]`, ErrSyntax},
		{"trailing-comma-object", `{"a":1,}`, ErrSyntax},
		{"raw-control", "\"a\x01b\"", ErrSyntax},
		{"raw-newline-in-string", "\"a\nb\"", ErrSyntax},
		{"escape-slash", `"\/"`, ErrSyntax},
		{"escape-uppercase-hex", `"\u000B"`, ErrSyntax},
		{"escape-short", `"\u01"`, ErrSyntax},
		{"escape-noncontrol", `"\u0041"`, ErrSyntax},
		{"escape-short-form-as-u", `"\u0009"`, ErrSyntax},
		{"escape-surrogate", `"\ud800"`, ErrSyntax},
		{"escape-surrogate-pair", `"\ud83d\ude00"`, ErrSyntax},
		{"u2028-raw", "\"a\u2028b\"", ErrLineSeparator},
		{"u2029-raw", "\"a\u2029b\"", ErrLineSeparator},
		{"invalid-utf8", string([]byte{'"', 0xff, '"'}), ErrInvalidString},
		{"int64-overflow", `9223372036854775808`, ErrUnsafeInteger},
		{"unescaped-tab-in-string", "\"a\tb\"", ErrSyntax},
		{"single-quotes", `{'a':1}`, ErrSyntax},
		{"missing-colon", `{"a" 1}`, ErrSyntax},
		{"bare-undefined", `undefined`, ErrSyntax},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := Parse([]byte(tc.input))
			if !errors.Is(err, tc.want) {
				t.Fatalf("Parse(%q) error = %v, want %v", tc.input, err, tc.want)
			}
		})
	}
}

func TestParserLimits(t *testing.T) {
	// Depth 13 rejected.
	deep := strings.Repeat("[", 13) + "1" + strings.Repeat("]", 13)
	if _, err := Parse([]byte(deep)); !errors.Is(err, ErrTooDeep) {
		t.Fatalf("depth 13: %v", err)
	}
	// Depth 12 accepted.
	ok := strings.Repeat("[", 12) + "1" + strings.Repeat("]", 12)
	if _, err := Parse([]byte(ok)); err != nil {
		t.Fatalf("depth 12: %v", err)
	}
	// 513 array items rejected.
	var sb strings.Builder
	sb.WriteByte('[')
	for i := 0; i < 513; i++ {
		if i > 0 {
			sb.WriteByte(',')
		}
		sb.WriteByte('0')
	}
	sb.WriteByte(']')
	if _, err := Parse([]byte(sb.String())); !errors.Is(err, ErrTooManyItems) {
		t.Fatalf("513 items: %v", err)
	}
	// Oversized input rejected.
	if _, err := Parse(make([]byte, MaxBytes+1)); !errors.Is(err, ErrTooLarge) {
		t.Fatalf("oversize: %v", err)
	}
}

func TestCompareUTF16(t *testing.T) {
	// U+10000 sorts before U+E000 in UTF-16 order (surrogate 0xD800 < 0xE000),
	// the reverse of UTF-8 byte order.
	if CompareUTF16("\U00010000", "") >= 0 {
		t.Fatal("U+10000 must sort before U+E000 in UTF-16 order")
	}
	if CompareUTF16("a", "a") != 0 {
		t.Fatal("equal strings must compare 0")
	}
	if CompareUTF16("a", "ab") >= 0 {
		t.Fatal("prefix must sort first")
	}
}

func TestEncodeIdempotentOnParse(t *testing.T) {
	inputs := []string{
		`null`, `true`, `false`, `0`, `-1`, `9007199254740991`,
		`""`, `"a\"b\\c\bd\te\nf\fg\rh"`, `"Aé中😀"`,
		`[]`, `{}`, `[1,[2,[3,[4]]]]`,
		`{"A":1,"a":2,"á":3,"𐀀":4,"":5}`,
	}
	for _, in := range inputs {
		v, err := Parse([]byte(in))
		if err != nil {
			t.Fatalf("Parse(%s): %v", in, err)
		}
		out, err := Encode(v)
		if err != nil {
			t.Fatalf("Encode(Parse(%s)): %v", in, err)
		}
		if string(out) != in {
			t.Fatalf("round-trip: got %s want %s", out, in)
		}
	}
}
