package keys

import (
	"crypto/ed25519"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"os"
	"testing"
)

// keyVectors are generated by scripts/gen-fixtures.cjs using node:crypto.
// Because Ed25519 signatures are deterministic, matching node's signature
// byte-for-byte proves interop in both directions: node verifies what Go
// signs (identical bytes), and Go verifies what node signs.
type keyVectorFile struct {
	Keys []struct {
		SeedHex       string `json:"seedHex"`
		PublicKeySpki string `json:"publicKeySpki"`
		SPKIDERHex    string `json:"spkiDerHex"`
		KeyID         string `json:"keyId"`
		DeviceID      string `json:"deviceId"`
	} `json:"keys"`
	Signatures []struct {
		SeedHex            string `json:"seedHex"`
		MessageName        string `json:"messageName"`
		MessageBase64url   string `json:"messageBase64url"`
		SignatureBase64url string `json:"signatureBase64url"`
	} `json:"signatures"`
	ECSPKIBase64url string `json:"ecSpkiBase64url"`
}

func loadKeyVectors(t *testing.T) keyVectorFile {
	t.Helper()
	raw, err := os.ReadFile("testdata/key_vectors.json")
	if err != nil {
		t.Fatalf("read key vectors: %v (run scripts/gen-fixtures.cjs)", err)
	}
	var vf keyVectorFile
	if err := json.Unmarshal(raw, &vf); err != nil {
		t.Fatalf("parse key vectors: %v", err)
	}
	if len(vf.Keys) == 0 || len(vf.Signatures) == 0 {
		t.Fatal("empty vectors")
	}
	return vf
}

func TestSPKIInteropWithNode(t *testing.T) {
	vf := loadKeyVectors(t)
	for _, kv := range vf.Keys {
		t.Run(kv.SeedHex[:8], func(t *testing.T) {
			seed, err := hex.DecodeString(kv.SeedHex)
			if err != nil {
				t.Fatal(err)
			}
			priv, err := PrivateFromSeed(seed)
			if err != nil {
				t.Fatal(err)
			}
			pub := Public(priv)

			// SPKI DER must be byte-identical to node's export.
			der, err := SPKIDER(pub)
			if err != nil {
				t.Fatal(err)
			}
			if hex.EncodeToString(der) != kv.SPKIDERHex {
				t.Fatalf("SPKI DER mismatch:\n go:   %s\n node: %s", hex.EncodeToString(der), kv.SPKIDERHex)
			}

			// base64url form must match.
			s, err := SPKIBase64url(pub)
			if err != nil {
				t.Fatal(err)
			}
			if s != kv.PublicKeySpki {
				t.Fatalf("SPKI base64url mismatch:\n go:   %s\n node: %s", s, kv.PublicKeySpki)
			}

			// Key ID and device ID derivation must match fleetAuth.js.
			keyID, err := KeyID(pub)
			if err != nil {
				t.Fatal(err)
			}
			if keyID != kv.KeyID {
				t.Fatalf("key ID mismatch: go %s node %s", keyID, kv.KeyID)
			}
			devID, err := DeviceID(pub)
			if err != nil {
				t.Fatal(err)
			}
			if devID != kv.DeviceID {
				t.Fatalf("device ID mismatch: go %s node %s", devID, kv.DeviceID)
			}

			// Parse must round-trip.
			pub2, der2, err := ParsePublicKeySPKI(kv.PublicKeySpki)
			if err != nil {
				t.Fatalf("ParsePublicKeySPKI: %v", err)
			}
			if !pub2.Equal(pub) || hex.EncodeToString(der2) != kv.SPKIDERHex {
				t.Fatal("SPKI parse round-trip mismatch")
			}
		})
	}
}

func TestSignatureInteropWithNode(t *testing.T) {
	vf := loadKeyVectors(t)
	for _, sv := range vf.Signatures {
		t.Run(sv.MessageName+"/"+sv.SeedHex[:8], func(t *testing.T) {
			seed, _ := hex.DecodeString(sv.SeedHex)
			priv, err := PrivateFromSeed(seed)
			if err != nil {
				t.Fatal(err)
			}
			msg, err := base64.RawURLEncoding.DecodeString(sv.MessageBase64url)
			if err != nil {
				t.Fatal(err)
			}
			nodeSig, err := base64.RawURLEncoding.DecodeString(sv.SignatureBase64url)
			if err != nil {
				t.Fatal(err)
			}

			// Go verifies node's signature.
			if !Verify(Public(priv), msg, nodeSig) {
				t.Fatal("Go failed to verify node signature")
			}
			// Go's signature must be byte-identical (deterministic Ed25519),
			// so node will verify Go-signed messages too.
			goSig := Sign(priv, msg)
			if !ed25519.Verify(Public(priv), msg, goSig) {
				t.Fatal("Go failed to verify its own signature")
			}
			if !bytesEqual(goSig, nodeSig) {
				t.Fatal("Go and node signatures differ")
			}
			enc, err := EncodeSignature(goSig)
			if err != nil {
				t.Fatal(err)
			}
			if enc != sv.SignatureBase64url {
				t.Fatal("base64url signature encoding mismatch")
			}
			// Tampered message must not verify.
			if len(msg) > 0 {
				bad := append([]byte(nil), msg...)
				bad[0] ^= 1
				if Verify(Public(priv), bad, nodeSig) {
					t.Fatal("verified signature over tampered message")
				}
			}
		})
	}
}

func bytesEqual(a, b []byte) bool {
	if len(a) != len(b) {
		return false
	}
	var v byte
	for i := range a {
		v |= a[i] ^ b[i]
	}
	return v == 0
}

func TestParsePublicKeySPKIRejects(t *testing.T) {
	vf := loadKeyVectors(t)
	valid := vf.Keys[0].PublicKeySpki

	// Valid key with padding added is non-canonical.
	if _, _, err := ParsePublicKeySPKI(valid + "="); !errors.Is(err, ErrInvalidPublicKey) {
		t.Fatalf("padded: %v", err)
	}
	// Wrong algorithm (P-256).
	if _, _, err := ParsePublicKeySPKI(vf.ECSPKIBase64url); !errors.Is(err, ErrInvalidPublicKey) {
		t.Fatalf("ec key: %v", err)
	}
	// Too short / bad alphabet / garbage DER.
	for _, s := range []string{
		"short",
		"!!!invalid!!!",
		base64.RawURLEncoding.EncodeToString([]byte("not a der structure at all, padded to pass length checks!!")),
		"",
	} {
		if _, _, err := ParsePublicKeySPKI(s); err == nil {
			t.Fatalf("accepted %q", s)
		}
	}
	// Truncated valid key.
	if _, _, err := ParsePublicKeySPKI(valid[:44]); err == nil {
		t.Fatal("accepted truncated key")
	}
}

func TestParsePrivateKey(t *testing.T) {
	priv, err := Generate()
	if err != nil {
		t.Fatal(err)
	}
	raw := []byte(priv)
	parsed, err := ParsePrivateKey(raw)
	if err != nil {
		t.Fatalf("ParsePrivateKey: %v", err)
	}
	if !parsed.Equal(priv) {
		t.Fatal("round-trip mismatch")
	}
	// Wrong length.
	if _, err := ParsePrivateKey(raw[:32]); !errors.Is(err, ErrInvalidPrivateKey) {
		t.Fatalf("short key: %v", err)
	}
	// Corrupted public half.
	bad := append([]byte(nil), raw...)
	bad[63] ^= 1
	if _, err := ParsePrivateKey(bad); !errors.Is(err, ErrInvalidPrivateKey) {
		t.Fatalf("corrupted key: %v", err)
	}
}

func TestParseSignature(t *testing.T) {
	priv, _ := Generate()
	sig := Sign(priv, []byte("msg"))
	enc, err := EncodeSignature(sig)
	if err != nil {
		t.Fatal(err)
	}
	if len(enc) != 86 {
		t.Fatalf("signature encoding length = %d, want 86", len(enc))
	}
	dec, err := ParseSignature(enc)
	if err != nil {
		t.Fatal(err)
	}
	if !bytesEqual(dec, sig) {
		t.Fatal("round-trip mismatch")
	}
	for _, bad := range []string{"", "short", enc + "=", enc[:50]} {
		if _, err := ParseSignature(bad); !errors.Is(err, ErrInvalidSignature) {
			t.Fatalf("accepted %q", bad)
		}
	}
}
