// Native catalogue snapshot: StatsKey/Models/LiftingExerciseCatalog.swift, 2026-09-15.
// IDs, muscle groups, aliases, and timed measures match the iOS catalogue.
export const NATIVE_STRENGTH_CATALOG = [
  {"id":"bb-bench-press","name":"Bench Press (Barbell)","equipment":"barbell","primaryMuscles":["chest"],"secondaryMuscles":["triceps","shoulders"],"aliases":["flat bench"],"measure":"reps"},
  {"id":"bb-incline-bench-press","name":"Incline Bench Press (Barbell)","equipment":"barbell","primaryMuscles":["chest"],"secondaryMuscles":["shoulders","triceps"],"aliases":[],"measure":"reps"},
  {"id":"bb-decline-bench-press","name":"Decline Bench Press (Barbell)","equipment":"barbell","primaryMuscles":["chest"],"secondaryMuscles":["triceps"],"aliases":[],"measure":"reps"},
  {"id":"db-bench-press","name":"Bench Press (Dumbbell)","equipment":"dumbbell","primaryMuscles":["chest"],"secondaryMuscles":["triceps","shoulders"],"aliases":[],"measure":"reps"},
  {"id":"db-incline-bench-press","name":"Incline Bench Press (Dumbbell)","equipment":"dumbbell","primaryMuscles":["chest"],"secondaryMuscles":["shoulders","triceps"],"aliases":[],"measure":"reps"},
  {"id":"db-chest-fly","name":"Chest Fly (Dumbbell)","equipment":"dumbbell","primaryMuscles":["chest"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"machine-chest-press","name":"Chest Press (Machine)","equipment":"machine","primaryMuscles":["chest"],"secondaryMuscles":["triceps"],"aliases":[],"measure":"reps"},
  {"id":"machine-pec-deck","name":"Pec Deck (Machine)","equipment":"machine","primaryMuscles":["chest"],"secondaryMuscles":[],"aliases":["butterfly","machine fly"],"measure":"reps"},
  {"id":"cable-fly","name":"Cable Fly","equipment":"cable","primaryMuscles":["chest"],"secondaryMuscles":[],"aliases":["cable crossover"],"measure":"reps"},
  {"id":"smith-bench-press","name":"Bench Press (Smith Machine)","equipment":"smithMachine","primaryMuscles":["chest"],"secondaryMuscles":["triceps"],"aliases":[],"measure":"reps"},
  {"id":"bw-push-up","name":"Push-Up","equipment":"bodyweight","primaryMuscles":["chest"],"secondaryMuscles":["triceps","shoulders","core"],"aliases":[],"measure":"reps"},
  {"id":"bw-dip","name":"Dip","equipment":"bodyweight","primaryMuscles":["chest","triceps"],"secondaryMuscles":["shoulders"],"aliases":["chest dip"],"measure":"reps"},
  {"id":"machine-assisted-dip","name":"Assisted Dip (Machine)","equipment":"machine","primaryMuscles":["chest","triceps"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"bw-incline-push-up","name":"Incline Push-Up","equipment":"bodyweight","primaryMuscles":["chest"],"secondaryMuscles":["triceps","shoulders","core"],"aliases":[],"measure":"reps"},
  {"id":"bw-knee-push-up","name":"Knee Push-Up","equipment":"bodyweight","primaryMuscles":["chest"],"secondaryMuscles":["triceps","shoulders"],"aliases":[],"measure":"reps"},
  {"id":"db-floor-press","name":"Floor Press (Dumbbell)","equipment":"dumbbell","primaryMuscles":["chest","triceps"],"secondaryMuscles":["shoulders"],"aliases":[],"measure":"reps"},
  {"id":"bb-deadlift","name":"Deadlift (Barbell)","equipment":"barbell","primaryMuscles":["back","hamstrings","glutes"],"secondaryMuscles":["core","forearms"],"aliases":["conventional deadlift"],"measure":"reps"},
  {"id":"bb-romanian-deadlift","name":"Romanian Deadlift (Barbell)","equipment":"barbell","primaryMuscles":["hamstrings","glutes"],"secondaryMuscles":["back"],"aliases":["RDL"],"measure":"reps"},
  {"id":"db-romanian-deadlift","name":"Romanian Deadlift (Dumbbell)","equipment":"dumbbell","primaryMuscles":["hamstrings","glutes"],"secondaryMuscles":["back"],"aliases":[],"measure":"reps"},
  {"id":"bb-bent-over-row","name":"Bent-Over Row (Barbell)","equipment":"barbell","primaryMuscles":["back"],"secondaryMuscles":["biceps"],"aliases":["barbell row"],"measure":"reps"},
  {"id":"db-row","name":"One-Arm Row (Dumbbell)","equipment":"dumbbell","primaryMuscles":["back"],"secondaryMuscles":["biceps"],"aliases":["dumbbell row"],"measure":"reps"},
  {"id":"machine-seated-row","name":"Seated Row (Machine)","equipment":"machine","primaryMuscles":["back"],"secondaryMuscles":["biceps"],"aliases":[],"measure":"reps"},
  {"id":"cable-seated-row","name":"Seated Cable Row","equipment":"cable","primaryMuscles":["back"],"secondaryMuscles":["biceps"],"aliases":[],"measure":"reps"},
  {"id":"cable-lat-pulldown","name":"Lat Pulldown","equipment":"cable","primaryMuscles":["back"],"secondaryMuscles":["biceps"],"aliases":["pulldown"],"measure":"reps"},
  {"id":"machine-lat-pulldown","name":"Lat Pulldown (Machine)","equipment":"machine","primaryMuscles":["back"],"secondaryMuscles":["biceps"],"aliases":[],"measure":"reps"},
  {"id":"bw-pull-up","name":"Pull-Up","equipment":"bodyweight","primaryMuscles":["back"],"secondaryMuscles":["biceps","forearms"],"aliases":[],"measure":"reps"},
  {"id":"bw-chin-up","name":"Chin-Up","equipment":"bodyweight","primaryMuscles":["back","biceps"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"machine-assisted-pull-up","name":"Assisted Pull-Up (Machine)","equipment":"machine","primaryMuscles":["back"],"secondaryMuscles":["biceps"],"aliases":[],"measure":"reps"},
  {"id":"cable-straight-arm-pulldown","name":"Straight-Arm Pulldown","equipment":"cable","primaryMuscles":["back"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"bb-t-bar-row","name":"T-Bar Row","equipment":"barbell","primaryMuscles":["back"],"secondaryMuscles":["biceps"],"aliases":[],"measure":"reps"},
  {"id":"machine-back-extension","name":"Back Extension (Machine)","equipment":"machine","primaryMuscles":["back","glutes"],"secondaryMuscles":["hamstrings"],"aliases":["hyperextension"],"measure":"reps"},
  {"id":"bb-rack-pull","name":"Rack Pull (Barbell)","equipment":"barbell","primaryMuscles":["back"],"secondaryMuscles":["forearms","glutes"],"aliases":[],"measure":"reps"},
  {"id":"bb-shrug","name":"Shrug (Barbell)","equipment":"barbell","primaryMuscles":["back"],"secondaryMuscles":["forearms"],"aliases":[],"measure":"reps"},
  {"id":"db-shrug","name":"Shrug (Dumbbell)","equipment":"dumbbell","primaryMuscles":["back"],"secondaryMuscles":["forearms"],"aliases":[],"measure":"reps"},
  {"id":"bw-inverted-row","name":"Inverted Row","equipment":"bodyweight","primaryMuscles":["back"],"secondaryMuscles":["biceps","core"],"aliases":["bodyweight row"],"measure":"reps"},
  {"id":"db-chest-supported-row","name":"Chest-Supported Row (Dumbbell)","equipment":"dumbbell","primaryMuscles":["back"],"secondaryMuscles":["biceps"],"aliases":[],"measure":"reps"},
  {"id":"bb-overhead-press","name":"Overhead Press (Barbell)","equipment":"barbell","primaryMuscles":["shoulders"],"secondaryMuscles":["triceps","core"],"aliases":["OHP","military press"],"measure":"reps"},
  {"id":"db-shoulder-press","name":"Shoulder Press (Dumbbell)","equipment":"dumbbell","primaryMuscles":["shoulders"],"secondaryMuscles":["triceps"],"aliases":[],"measure":"reps"},
  {"id":"machine-shoulder-press","name":"Shoulder Press (Machine)","equipment":"machine","primaryMuscles":["shoulders"],"secondaryMuscles":["triceps"],"aliases":[],"measure":"reps"},
  {"id":"db-lateral-raise","name":"Lateral Raise (Dumbbell)","equipment":"dumbbell","primaryMuscles":["shoulders"],"secondaryMuscles":[],"aliases":["side raise"],"measure":"reps"},
  {"id":"cable-lateral-raise","name":"Lateral Raise (Cable)","equipment":"cable","primaryMuscles":["shoulders"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"machine-lateral-raise","name":"Lateral Raise (Machine)","equipment":"machine","primaryMuscles":["shoulders"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"db-front-raise","name":"Front Raise (Dumbbell)","equipment":"dumbbell","primaryMuscles":["shoulders"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"db-rear-delt-fly","name":"Rear Delt Fly (Dumbbell)","equipment":"dumbbell","primaryMuscles":["shoulders"],"secondaryMuscles":["back"],"aliases":[],"measure":"reps"},
  {"id":"machine-reverse-pec-deck","name":"Reverse Pec Deck (Machine)","equipment":"machine","primaryMuscles":["shoulders"],"secondaryMuscles":["back"],"aliases":["rear delt machine"],"measure":"reps"},
  {"id":"cable-face-pull","name":"Face Pull (Cable)","equipment":"cable","primaryMuscles":["shoulders"],"secondaryMuscles":["back"],"aliases":[],"measure":"reps"},
  {"id":"bb-upright-row","name":"Upright Row (Barbell)","equipment":"barbell","primaryMuscles":["shoulders"],"secondaryMuscles":["back"],"aliases":[],"measure":"reps"},
  {"id":"db-arnold-press","name":"Arnold Press (Dumbbell)","equipment":"dumbbell","primaryMuscles":["shoulders"],"secondaryMuscles":["triceps"],"aliases":[],"measure":"reps"},
  {"id":"bb-curl","name":"Curl (Barbell)","equipment":"barbell","primaryMuscles":["biceps"],"secondaryMuscles":["forearms"],"aliases":["barbell curl"],"measure":"reps"},
  {"id":"db-curl","name":"Curl (Dumbbell)","equipment":"dumbbell","primaryMuscles":["biceps"],"secondaryMuscles":["forearms"],"aliases":["bicep curl"],"measure":"reps"},
  {"id":"db-hammer-curl","name":"Hammer Curl (Dumbbell)","equipment":"dumbbell","primaryMuscles":["biceps","forearms"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"cable-curl","name":"Curl (Cable)","equipment":"cable","primaryMuscles":["biceps"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"machine-preacher-curl","name":"Preacher Curl (Machine)","equipment":"machine","primaryMuscles":["biceps"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"bb-preacher-curl","name":"Preacher Curl (Barbell)","equipment":"barbell","primaryMuscles":["biceps"],"secondaryMuscles":[],"aliases":["EZ bar preacher curl"],"measure":"reps"},
  {"id":"db-incline-curl","name":"Incline Curl (Dumbbell)","equipment":"dumbbell","primaryMuscles":["biceps"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"db-concentration-curl","name":"Concentration Curl (Dumbbell)","equipment":"dumbbell","primaryMuscles":["biceps"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"cable-triceps-pushdown","name":"Triceps Pushdown (Cable)","equipment":"cable","primaryMuscles":["triceps"],"secondaryMuscles":[],"aliases":["pushdown","rope pushdown"],"measure":"reps"},
  {"id":"bb-close-grip-bench-press","name":"Close-Grip Bench Press (Barbell)","equipment":"barbell","primaryMuscles":["triceps"],"secondaryMuscles":["chest"],"aliases":[],"measure":"reps"},
  {"id":"db-overhead-triceps-extension","name":"Overhead Triceps Extension (Dumbbell)","equipment":"dumbbell","primaryMuscles":["triceps"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"cable-overhead-triceps-extension","name":"Overhead Triceps Extension (Cable)","equipment":"cable","primaryMuscles":["triceps"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"bb-skull-crusher","name":"Skull Crusher (Barbell)","equipment":"barbell","primaryMuscles":["triceps"],"secondaryMuscles":[],"aliases":["lying triceps extension"],"measure":"reps"},
  {"id":"machine-triceps-extension","name":"Triceps Extension (Machine)","equipment":"machine","primaryMuscles":["triceps"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"bw-bench-dip","name":"Bench Dip","equipment":"bodyweight","primaryMuscles":["triceps"],"secondaryMuscles":["chest"],"aliases":[],"measure":"reps"},
  {"id":"db-triceps-kickback","name":"Triceps Kickback (Dumbbell)","equipment":"dumbbell","primaryMuscles":["triceps"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"bb-wrist-curl","name":"Wrist Curl (Barbell)","equipment":"barbell","primaryMuscles":["forearms"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"db-farmers-carry","name":"Farmer's Carry (Dumbbell)","equipment":"dumbbell","primaryMuscles":["forearms","core"],"secondaryMuscles":["back"],"aliases":["farmers walk"],"measure":"time"},
  {"id":"bw-dead-hang","name":"Dead Hang","equipment":"bodyweight","primaryMuscles":["forearms"],"secondaryMuscles":["back","shoulders"],"aliases":["bar hang"],"measure":"time"},
  {"id":"bb-back-squat","name":"Back Squat (Barbell)","equipment":"barbell","primaryMuscles":["quads","glutes"],"secondaryMuscles":["hamstrings","core"],"aliases":["squat"],"measure":"reps"},
  {"id":"bb-front-squat","name":"Front Squat (Barbell)","equipment":"barbell","primaryMuscles":["quads"],"secondaryMuscles":["glutes","core"],"aliases":[],"measure":"reps"},
  {"id":"smith-squat","name":"Squat (Smith Machine)","equipment":"smithMachine","primaryMuscles":["quads","glutes"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"db-goblet-squat","name":"Goblet Squat (Dumbbell)","equipment":"dumbbell","primaryMuscles":["quads","glutes"],"secondaryMuscles":["core"],"aliases":[],"measure":"reps"},
  {"id":"machine-leg-press","name":"Leg Press (Machine)","equipment":"machine","primaryMuscles":["quads","glutes"],"secondaryMuscles":["hamstrings"],"aliases":[],"measure":"reps"},
  {"id":"machine-hack-squat","name":"Hack Squat (Machine)","equipment":"machine","primaryMuscles":["quads"],"secondaryMuscles":["glutes"],"aliases":[],"measure":"reps"},
  {"id":"machine-leg-extension","name":"Leg Extension (Machine)","equipment":"machine","primaryMuscles":["quads"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"db-lunge","name":"Lunge (Dumbbell)","equipment":"dumbbell","primaryMuscles":["quads","glutes"],"secondaryMuscles":["hamstrings"],"aliases":["walking lunge"],"measure":"reps"},
  {"id":"bb-lunge","name":"Lunge (Barbell)","equipment":"barbell","primaryMuscles":["quads","glutes"],"secondaryMuscles":["hamstrings"],"aliases":[],"measure":"reps"},
  {"id":"db-bulgarian-split-squat","name":"Bulgarian Split Squat (Dumbbell)","equipment":"dumbbell","primaryMuscles":["quads","glutes"],"secondaryMuscles":["hamstrings"],"aliases":[],"measure":"reps"},
  {"id":"db-step-up","name":"Step-Up (Dumbbell)","equipment":"dumbbell","primaryMuscles":["quads","glutes"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"bw-squat","name":"Squat (Bodyweight)","equipment":"bodyweight","primaryMuscles":["quads","glutes"],"secondaryMuscles":[],"aliases":["air squat"],"measure":"reps"},
  {"id":"bw-lunge","name":"Lunge (Bodyweight)","equipment":"bodyweight","primaryMuscles":["quads","glutes"],"secondaryMuscles":["hamstrings"],"aliases":["walking lunge"],"measure":"reps"},
  {"id":"bw-reverse-lunge","name":"Reverse Lunge (Bodyweight)","equipment":"bodyweight","primaryMuscles":["quads","glutes"],"secondaryMuscles":["hamstrings"],"aliases":[],"measure":"reps"},
  {"id":"db-reverse-lunge","name":"Reverse Lunge (Dumbbell)","equipment":"dumbbell","primaryMuscles":["quads","glutes"],"secondaryMuscles":["hamstrings"],"aliases":[],"measure":"reps"},
  {"id":"bw-split-squat","name":"Split Squat (Bodyweight)","equipment":"bodyweight","primaryMuscles":["quads","glutes"],"secondaryMuscles":["hamstrings"],"aliases":[],"measure":"reps"},
  {"id":"bw-bulgarian-split-squat","name":"Bulgarian Split Squat (Bodyweight)","equipment":"bodyweight","primaryMuscles":["quads","glutes"],"secondaryMuscles":["hamstrings"],"aliases":["rear foot elevated split squat"],"measure":"reps"},
  {"id":"bw-step-up","name":"Step-Up (Bodyweight)","equipment":"bodyweight","primaryMuscles":["quads","glutes"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"machine-seated-leg-curl","name":"Seated Leg Curl (Machine)","equipment":"machine","primaryMuscles":["hamstrings"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"machine-lying-leg-curl","name":"Lying Leg Curl (Machine)","equipment":"machine","primaryMuscles":["hamstrings"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"bb-hip-thrust","name":"Hip Thrust (Barbell)","equipment":"barbell","primaryMuscles":["glutes"],"secondaryMuscles":["hamstrings"],"aliases":[],"measure":"reps"},
  {"id":"machine-hip-thrust","name":"Hip Thrust (Machine)","equipment":"machine","primaryMuscles":["glutes"],"secondaryMuscles":["hamstrings"],"aliases":[],"measure":"reps"},
  {"id":"machine-hip-abduction","name":"Hip Abduction (Machine)","equipment":"machine","primaryMuscles":["glutes"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"machine-hip-adduction","name":"Hip Adduction (Machine)","equipment":"machine","primaryMuscles":["glutes"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"cable-pull-through","name":"Cable Pull-Through","equipment":"cable","primaryMuscles":["glutes","hamstrings"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"bb-good-morning","name":"Good Morning (Barbell)","equipment":"barbell","primaryMuscles":["hamstrings"],"secondaryMuscles":["back","glutes"],"aliases":[],"measure":"reps"},
  {"id":"bw-glute-bridge","name":"Glute Bridge","equipment":"bodyweight","primaryMuscles":["glutes"],"secondaryMuscles":["hamstrings"],"aliases":[],"measure":"reps"},
  {"id":"bw-nordic-curl","name":"Nordic Curl","equipment":"bodyweight","primaryMuscles":["hamstrings"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"bw-single-leg-glute-bridge","name":"Single-Leg Glute Bridge","equipment":"bodyweight","primaryMuscles":["glutes"],"secondaryMuscles":["hamstrings","core"],"aliases":[],"measure":"reps"},
  {"id":"db-single-leg-romanian-deadlift","name":"Single-Leg Romanian Deadlift (Dumbbell)","equipment":"dumbbell","primaryMuscles":["hamstrings","glutes"],"secondaryMuscles":["core","back"],"aliases":[],"measure":"reps"},
  {"id":"machine-standing-calf-raise","name":"Standing Calf Raise (Machine)","equipment":"machine","primaryMuscles":["calves"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"machine-seated-calf-raise","name":"Seated Calf Raise (Machine)","equipment":"machine","primaryMuscles":["calves"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"machine-leg-press-calf-raise","name":"Calf Raise on Leg Press","equipment":"machine","primaryMuscles":["calves"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"bw-calf-raise","name":"Calf Raise (Bodyweight)","equipment":"bodyweight","primaryMuscles":["calves"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"db-calf-raise","name":"Calf Raise (Dumbbell)","equipment":"dumbbell","primaryMuscles":["calves"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"bw-plank","name":"Plank","equipment":"bodyweight","primaryMuscles":["core"],"secondaryMuscles":[],"aliases":[],"measure":"time"},
  {"id":"bw-side-plank","name":"Side Plank","equipment":"bodyweight","primaryMuscles":["core"],"secondaryMuscles":[],"aliases":[],"measure":"time"},
  {"id":"bw-hollow-hold","name":"Hollow Hold","equipment":"bodyweight","primaryMuscles":["core"],"secondaryMuscles":[],"aliases":["hollow body hold"],"measure":"time"},
  {"id":"bw-wall-sit","name":"Wall Sit","equipment":"bodyweight","primaryMuscles":["quads"],"secondaryMuscles":["glutes"],"aliases":[],"measure":"time"},
  {"id":"bw-l-sit","name":"L-Sit","equipment":"bodyweight","primaryMuscles":["core"],"secondaryMuscles":["triceps"],"aliases":[],"measure":"time"},
  {"id":"bw-hanging-leg-raise","name":"Hanging Leg Raise","equipment":"bodyweight","primaryMuscles":["core"],"secondaryMuscles":["forearms"],"aliases":[],"measure":"reps"},
  {"id":"cable-crunch","name":"Cable Crunch","equipment":"cable","primaryMuscles":["core"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"machine-ab-crunch","name":"Ab Crunch (Machine)","equipment":"machine","primaryMuscles":["core"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"bw-sit-up","name":"Sit-Up","equipment":"bodyweight","primaryMuscles":["core"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"bw-russian-twist","name":"Russian Twist","equipment":"bodyweight","primaryMuscles":["core"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"cable-wood-chop","name":"Cable Wood Chop","equipment":"cable","primaryMuscles":["core"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"bb-ab-rollout","name":"Ab Rollout","equipment":"barbell","primaryMuscles":["core"],"secondaryMuscles":[],"aliases":["ab wheel"],"measure":"reps"},
  {"id":"bw-crunch","name":"Crunch","equipment":"bodyweight","primaryMuscles":["core"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"bw-bicycle-crunch","name":"Bicycle Crunch","equipment":"bodyweight","primaryMuscles":["core"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"bw-dead-bug","name":"Dead Bug","equipment":"bodyweight","primaryMuscles":["core"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"bw-bird-dog","name":"Bird Dog","equipment":"bodyweight","primaryMuscles":["core","back"],"secondaryMuscles":["glutes"],"aliases":[],"measure":"reps"},
  {"id":"cable-pallof-press","name":"Pallof Press (Cable)","equipment":"cable","primaryMuscles":["core"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"db-suitcase-carry","name":"Suitcase Carry (Dumbbell)","equipment":"dumbbell","primaryMuscles":["core","forearms"],"secondaryMuscles":["back"],"aliases":["suitcase walk"],"measure":"time"},
  {"id":"kb-swing","name":"Kettlebell Swing","equipment":"kettlebell","primaryMuscles":["glutes","hamstrings"],"secondaryMuscles":["core","back"],"aliases":[],"measure":"reps"},
  {"id":"kb-goblet-squat","name":"Goblet Squat (Kettlebell)","equipment":"kettlebell","primaryMuscles":["quads","glutes"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"kb-clean-and-press","name":"Clean and Press (Kettlebell)","equipment":"kettlebell","primaryMuscles":["fullBody"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"bb-clean","name":"Power Clean (Barbell)","equipment":"barbell","primaryMuscles":["fullBody"],"secondaryMuscles":["back","quads"],"aliases":[],"measure":"reps"},
  {"id":"bb-snatch","name":"Snatch (Barbell)","equipment":"barbell","primaryMuscles":["fullBody"],"secondaryMuscles":["shoulders","back"],"aliases":[],"measure":"reps"},
  {"id":"bb-push-press","name":"Push Press (Barbell)","equipment":"barbell","primaryMuscles":["shoulders","fullBody"],"secondaryMuscles":["triceps"],"aliases":[],"measure":"reps"},
  {"id":"bb-thruster","name":"Thruster (Barbell)","equipment":"barbell","primaryMuscles":["fullBody"],"secondaryMuscles":["quads","shoulders"],"aliases":[],"measure":"reps"},
  {"id":"kb-deadlift","name":"Deadlift (Kettlebell)","equipment":"kettlebell","primaryMuscles":["glutes","hamstrings"],"secondaryMuscles":["back","core"],"aliases":[],"measure":"reps"},
  {"id":"kb-suitcase-carry","name":"Suitcase Carry (Kettlebell)","equipment":"kettlebell","primaryMuscles":["core","forearms"],"secondaryMuscles":["back"],"aliases":["suitcase walk"],"measure":"time"},
  {"id":"db-thruster","name":"Thruster (Dumbbell)","equipment":"dumbbell","primaryMuscles":["fullBody"],"secondaryMuscles":["quads","shoulders"],"aliases":[],"measure":"reps"},
  {"id":"bw-burpee","name":"Burpee","equipment":"bodyweight","primaryMuscles":["fullBody"],"secondaryMuscles":["chest","quads","core"],"aliases":[],"measure":"reps"},
  {"id":"band-pull-apart","name":"Band Pull-Apart","equipment":"band","primaryMuscles":["shoulders"],"secondaryMuscles":["back"],"aliases":[],"measure":"reps"},
  {"id":"band-row","name":"Band Row","equipment":"band","primaryMuscles":["back"],"secondaryMuscles":["biceps"],"aliases":[],"measure":"reps"},
  {"id":"band-chest-press","name":"Chest Press (Band)","equipment":"band","primaryMuscles":["chest"],"secondaryMuscles":["triceps","shoulders"],"aliases":[],"measure":"reps"},
  {"id":"band-curl","name":"Curl (Band)","equipment":"band","primaryMuscles":["biceps"],"secondaryMuscles":["forearms"],"aliases":[],"measure":"reps"},
  {"id":"band-triceps-extension","name":"Triceps Extension (Band)","equipment":"band","primaryMuscles":["triceps"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
  {"id":"band-lateral-walk","name":"Lateral Band Walk","equipment":"band","primaryMuscles":["glutes"],"secondaryMuscles":[],"aliases":["side steps"],"measure":"reps"},
  {"id":"band-pallof-press","name":"Pallof Press (Band)","equipment":"band","primaryMuscles":["core"],"secondaryMuscles":[],"aliases":[],"measure":"reps"},
] as const
